--
-- Database: `musicrec`
--

-- --------------------------------------------------------

--
-- Table structure for table `emotions`
--

CREATE TABLE `emotions` (
  `name` varchar(23) DEFAULT NULL,
  `emotions` varchar(137) DEFAULT NULL
) 

--
-- Table structure for table `music`
--

CREATE TABLE `music` (
  `name` varchar(20) DEFAULT NULL,
  `link` varchar(400) NOT NULL,
  `artist` varchar(40) NOT NULL,
  `list` varchar(40) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `playlist`
--

CREATE TABLE `playlist` (
  `playlist` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `playlist`
--

INSERT INTO `playlist` (`playlist`) VALUES
('hot-100'),
('billboard-200'),
('artist-100'),
('social-50'),
('streaming-songs'),
('radio-songs'),
('digital-song-sales'),
('on-demand-songs'),
('top-album-sales'),
('current-albums'),
('catalog-albums'),
('independent-albums'),
('soundtracks'),
('vinyl-albums'),
('greatest-billboard-200-albums'),
('greatest-billboard-200-artists'),
('greatest-hot-100-singles'),
('greatest-hot-100-artists'),
('greatest-hot-100-songs-by-women'),
('greatest-hot-100-women-artists'),
('greatest-billboard-200-albums-by-women'),
('greatest-billboard-200-women-artists'),
('greatest-billboards-top-songs-80s'),
('greatest-billboards-top-songs-90s'),
('greatest-of-all-time-pop-songs'),
('greatest-of-all-time-pop-songs-artists'),
('greatest-adult-pop-songs'),
('greatest-adult-pop-artists'),
('greatest-country-songs'),
('greatest-country-albums'),
('greatest-country-artists'),
('greatest-hot-latin-songs'),
('greatest-hot-latin-songs-artists'),
('greatest-top-dance-club-artists'),
('greatest-r-b-hip-hop-songs'),
('greatest-r-b-hip-hop-albums'),
('greatest-r-b-hip-hop-artists'),
('greatest-alternative-songs'),
('greatest-alternative-artists'),
('pop-songs'),
('pop-digital-song-sales'),
('adult-contemporary'),
('hot-adult-contemporary-recurrents'),
('adult-pop-songs'),
('hot-adult-40-recurrents'),
('country-songs'),
('country-albums'),
('country-album-sales'),
('country-catalog-albums'),
('country-streaming-songs'),
('country-airplay'),
('country-recurrent-airplay'),
('country-digital-song-sales'),
('bluegrass-albums'),
('americana-folk-albums'),
('americana-folk-album-sales'),
('rock-songs'),
('rock-albums'),
('rock-album-sales'),
('rock-streaming-songs'),
('rock-airplay'),
('rock-digital-song-sales'),
('alternative-songs'),
('alternative-albums'),
('alternative-album-sales'),
('alternative-digital-song-sales'),
('triple-a'),
('hot-mainstream-rock-tracks'),
('hard-rock-albums'),
('hard-rock-album-sales'),
('hard-rock-digital-song-sales'),
('r-b-hip-hop-songs'),
('r-b-hip-hop-albums'),
('randb-hip-hop-album-sales'),
('r-and-b-hip-hop-catalog-albums'),
('r-and-b-hip-hop-streaming-songs'),
('hot-r-and-b-hip-hop-airplay'),
('hot-r-and-b-hip-hop-recurrent-airplay'),
('r-and-b-hip-hop-digital-song-sales'),
('r-and-b-songs'),
('r-and-b-albums'),
('randb-album-sales'),
('r-and-b-streaming-songs'),
('r-and-b-digital-song-sales'),
('rap-song'),
('rap-albums'),
('rap-album-sales'),
('rap-streaming-songs'),
('hot-rap-tracks'),
('rap-digital-song-sales'),
('mainstream-r-and-b-hip-hop'),
('hot-adult-r-and-b-airplay'),
('rhythmic-40'),
('latin-songs'),
('latin-albums'),
('latin-album-sales'),
('latin-streaming-songs'),
('latin-airplay'),
('latin-recurrent-airplay'),
('latin-digital-song-sales'),
('regional-mexican-albums'),
('latin-regional-mexican-airplay'),
('regional-mexican-digital-song-sales'),
('latin-pop-albums'),
('latin-pop-airplay'),
('latin-pop-digital-song-sales'),
('tropical-albums'),
('latin-tropical-airplay'),
('tropical-digital-song-sales'),
('latin-rhythm-albums'),
('latin-rhythm-airplay'),
('latin-rhythm-digital-song-sales'),
('dance-electronic-songs'),
('dance-electronic-albums'),
('dance-electronic-album-sales'),
('dance-electronic-streaming-songs'),
('dance-electronic-digital-song-sales'),
('hot-dance-airplay'),
('dance-club-play-songs'),
('christian-songs'),
('christian-albums'),
('christian-album-sales'),
('christian-streaming-songs'),
('christian-airplay'),
('christian-digital-song-sales'),
('hot-christian-adult-contemporary'),
('gospel-songs'),
('gospel-albums'),
('gospel-album-sales'),
('gospel-streaming-songs'),
('gospel-airplay'),
('gospel-digital-song-sales'),
('classical-albums'),
('classical-crossover-albums'),
('traditional-classic-albums'),
('classical-budget-midline-albums'),
('classical-digital-song-sales'),
('jazz-albums'),
('contemporary-jazz'),
('traditional-jazz-albums'),
('jazz-songs'),
('jazz-digital-song-sales'),
('emerging-artists'),
('heatseekers-albums'),
('heatseekers-east-north-central'),
('heatseekers-middle-atlantic'),
('heatseekers-mountain'),
('heatseekers-northeast'),
('heatseekers-pacific'),
('heatseekers-south-atlantic'),
('heatseekers-south-central'),
('heatseekers-west-north-central'),
('lyricfind-global'),
('lyricfind-us'),
('next-big-sound-25'),
('bandsintown-rising-us'),
('bandsintown-rising-global'),
('bandsintown-top-us'),
('bandsintown-top-global'),
('hot-holiday-songs'),
('holiday-albums'),
('holiday-album-sales'),
('holiday-streaming-songs'),
('holiday-songs'),
('holiday-season-digital-song-sales'),
('summer-songs'),
('canadian-hot-100'),
('canadian-albums'),
('hot-canada-digital-song-sales'),
('canada-emerging-artists'),
('canada-ac'),
('canada-all-format-airplay'),
('canada-chr-top-40'),
('canada-country'),
('canada-hot-ac'),
('canada-rock'),
('mexico'),
('mexico-ingles'),
('mexico-popular'),
('mexico-espanol'),
('japan-hot-100'),
('k-pop-hot-100'),
('billboard-china-social-chart'),
('billboard-argentina-hot-100'),
('official-uk-songs'),
('official-uk-albums'),
('uk-digital-song-sales'),
('euro-digital-song-sales'),
('austria-digital-songs-sales'),
('belgium-digital-songs-sales'),
('denmark-digital-song-sales'),
('finland-digital-song-sales'),
('france-digital-song-sales'),
('germany-songs'),
('german-albums'),
('germany-digital-song-sales'),
('greece-albums'),
('greece-digital-song-sales'),
('ireland-digital-song-sales'),
('italy-albums'),
('italy-digital-song-sales'),
('luxembourg-digital-song-sales'),
('netherlands-digital-song-sales'),
('norway-digital-song-sales'),
('portugal-digital-song-sales'),
('spain-digital-song-sales'),
('sweden-digital-song-sales'),
('switzerland-digital-song-sales'),
('australian-albums'),
('australia-digital-song-sales'),
('new-zealand-digital-song-sales'),
('blues-albums'),
('blues-digital-song-sales'),
('bubbling-under-hot-100-singles'),
('bubbling-under-r-and-b-hip-hop-singles'),
('cast-albums'),
('catalog-album-sales'),
('comedy-albums'),
('comedy-digital-track-sales'),
('compilation-albums'),
('digital-albums'),
('hot-singles-recurrents'),
('internet-albums'),
('kids-albums'),
('kid-digital-song-sales'),
('music-video'),
('new-age-albums'),
('new-age-digital-song-sales'),
('hot-100-recurrent-airplay'),
('reggae-albums'),
('reggae-digital-song-sales'),
('soundtrack-sales'),
('tastemaker-albums'),
('world-albums'),
('world-digital-song-sales');

-- --------------------------------------------------------
--
-- Indexes for table `music`
--
ALTER TABLE `music`
  ADD PRIMARY KEY (`id`);

